server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huhsway/spring-cloud-config
#spring:
#  application:
#    name: config-service
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: file:\\\C:\workspace\ecommerce\git-local-repo


