server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/workspace/native-file-repo
        git:
          uri: https://github.com/huhsway/spring-cloud-config

#spring:
#  application:
#    name: config-service
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: file:\\\C:\workspace\ecommerce\git-local-repo

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

